image: node:20

stages:
  - test

variables:
  BROWSERSTACK_USERNAME: $BROWSERSTACK_USERNAME
  BROWSERSTACK_ACCESS_KEY: $BROWSERSTACK_ACCESS_KEY

before_script:
  - npm install

local_tests:
  stage: test
  script:
    - npx wdio run local-wdio.conf.js
  artifacts:
    paths:
      - allure-results
      - screenshots/*

browserstack_tests:
  stage: test
  script:
    - npx wdio run browserStack-wdio.conf.js
  artifacts:
    paths:
      - allure-results
      - screenshots/*